#ifndef _MODELS_PREGEN_H
#define _MODELS_PREGEN_H
// This file should be auto-generated by gen_models too
// but it doesn' lol


void mdl_snowmanBody();
void mdl_snowmanHead();

void mdl_gas();

#endif
